# Generated by Django 5.2.13 on 2026-04-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoLaboratorio',
            fields=[
                ('id_activo', models.AutoField(primary_key=True, serialize=False)),
                ('num_serie', models.CharField(max_length=60, unique=True)),
                ('codigo_patrimonio', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'activo_laboratorio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('hora_ingreso', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('asistio', models.BooleanField()),
            ],
            options={
                'db_table': 'asistencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'facultad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('capacidad_total', models.IntegerField()),
                ('capacidad_ocupada', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'horario_disponible',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_dano', models.TextField()),
                ('fecha_reporte', models.DateTimeField()),
                ('estado_activo_post', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'incidencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_patrimonio', models.CharField(max_length=30, unique=True)),
                ('aforo_maximo', models.IntegerField()),
                ('habilitado', models.BooleanField()),
            ],
            options={
                'db_table': 'laboratorio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.BooleanField()),
            ],
            options={
                'db_table': 'password_reset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Penalizacion',
            fields=[
                ('id_penalizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
            ],
            options={
                'db_table': 'penalizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilDocente',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'perfil_docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('ciclo', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'perfil_estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_alumnos', models.IntegerField()),
                ('acepto_declaracion_jurada', models.BooleanField()),
                ('estado', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'reserva',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservaDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'reserva_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id_tipo_activo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_activo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoLaboratorio',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('min_equipos', models.IntegerField()),
                ('tipo_equipo_minimo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_laboratorio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('codigo_universitario', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
