# Generated by Django 5.2.13 on 2026-05-25 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaActivo',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'categoria_activo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configuracion_sistema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'facultad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoLaboratorio',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('min_equipos', models.IntegerField()),
                ('tipo_equipo_minimo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_laboratorio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.facultad')),
            ],
            options={
                'db_table': 'carrera',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id_laboratorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_patrimonio', models.CharField(max_length=30, unique=True)),
                ('aforo_maximo', models.IntegerField()),
                ('habilitado', models.BooleanField()),
                ('id_facultad', models.ForeignKey(db_column='id_facultad', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.facultad')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.tipolaboratorio')),
            ],
            options={
                'db_table': 'laboratorio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('capacidad_total', models.IntegerField()),
                ('capacidad_ocupada', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('id_laboratorio', models.ForeignKey(db_column='id_laboratorio', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.laboratorio')),
            ],
            options={
                'db_table': 'horario_disponible',
                'managed': True,
                'unique_together': {('id_laboratorio', 'fecha', 'hora_inicio')},
            },
        ),
        migrations.CreateModel(
            name='ActivoLaboratorio',
            fields=[
                ('id_activo', models.AutoField(primary_key=True, serialize=False)),
                ('num_serie', models.CharField(max_length=60, unique=True)),
                ('codigo_patrimonio', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField()),
                ('id_laboratorio', models.ForeignKey(db_column='id_laboratorio', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.laboratorio')),
            ],
            options={
                'db_table': 'activo_laboratorio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_alumnos', models.IntegerField()),
                ('acepto_declaracion_jurada', models.BooleanField()),
                ('estado', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('id_horario', models.ForeignKey(db_column='id_horario', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.horariodisponible')),
            ],
            options={
                'db_table': 'reserva',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id_asistencia', models.AutoField(primary_key=True, serialize=False)),
                ('hora_ingreso', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('asistio', models.BooleanField()),
                ('id_reserva', models.OneToOneField(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.reserva')),
            ],
            options={
                'db_table': 'asistencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReservaDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_activo', models.ForeignKey(db_column='id_activo', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.activolaboratorio')),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.reserva')),
            ],
            options={
                'db_table': 'reserva_detalle',
                'managed': True,
                'unique_together': {('id_reserva', 'id_activo')},
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_dano', models.TextField()),
                ('fecha_reporte', models.DateTimeField()),
                ('estado_activo_post', models.CharField(max_length=20)),
                ('id_activo', models.ForeignKey(db_column='id_activo', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.activolaboratorio')),
                ('id_detalle', models.ForeignKey(db_column='id_detalle', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.reservadetalle')),
            ],
            options={
                'db_table': 'incidencia',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id_tipo_activo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.categoriaactivo')),
            ],
            options={
                'db_table': 'tipo_activo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='activolaboratorio',
            name='id_tipo_activo',
            field=models.ForeignKey(db_column='id_tipo_activo', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.tipoactivo'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('codigo_universitario', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField()),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.rol')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='reservas.usuario')),
            ],
            options={
                'db_table': 'sesion_usuario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.usuario'),
        ),
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('ciclo', models.SmallIntegerField()),
                ('id_carrera', models.ForeignKey(db_column='id_carrera', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.carrera')),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.usuario')),
            ],
            options={
                'db_table': 'perfil_estudiante',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerfilDocente',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=100)),
                ('id_usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.usuario')),
            ],
            options={
                'db_table': 'perfil_docente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Penalizacion',
            fields=[
                ('id_penalizacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('id_reserva', models.OneToOneField(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.reserva')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.usuario')),
            ],
            options={
                'db_table': 'penalizacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.BooleanField()),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.usuario')),
            ],
            options={
                'db_table': 'password_reset',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialReserva',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.reserva')),
                ('usuario_cambio', models.ForeignKey(db_column='usuario_cambio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.usuario')),
            ],
            options={
                'db_table': 'historial_reserva',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialMantenimiento',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField()),
                ('id_activo', models.ForeignKey(db_column='id_activo', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.activolaboratorio')),
                ('id_incidencia', models.ForeignKey(blank=True, db_column='id_incidencia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.incidencia')),
                ('registrado_por', models.ForeignKey(db_column='registrado_por', on_delete=django.db.models.deletion.DO_NOTHING, to='reservas.usuario')),
            ],
            options={
                'db_table': 'historial_mantenimiento',
                'managed': True,
            },
        ),
    ]
