# Generated by Django 5.2.13 on 2026-05-13 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaActivo',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'categoria_activo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'configuracion_sistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialMantenimiento',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField()),
            ],
            options={
                'db_table': 'historial_mantenimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialReserva',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
                ('usuario_cambio', models.ForeignKey(db_column='usuario_cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservas.usuario')),
            ],
            options={
                'db_table': 'historial_reserva',
                'managed': True,
            },
        ),
    ]
