# Generated by Django 5.2.13 on 2026-05-13 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_categoriaactivo_configuracionsistema_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activolaboratorio',
            options={'managed': True},
        ),
    ]
