# Generated by Django 5.2.13 on 2026-04-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_usuario_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoLaboratorio',
            fields=[
                ('id_activo', models.AutoField(primary_key=True, serialize=False)),
                ('num_serie', models.CharField(max_length=60, unique=True)),
                ('codigo_patrimonio', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'activo_laboratorio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'carrera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'facultad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('capacidad_total', models.IntegerField()),
                ('capacidad_ocupada', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'horario_disponible',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('fecha_expiracion', models.DateTimeField()),
                ('usado', models.BooleanField()),
            ],
            options={
                'db_table': 'password_reset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilDocente',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'perfil_docente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilEstudiante',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('ciclo', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'perfil_estudiante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReservaDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'reserva_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoActivo',
            fields=[
                ('id_tipo_activo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tipo_activo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoLaboratorio',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('min_equipos', models.IntegerField()),
                ('tipo_equipo_minimo', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_laboratorio',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='reservaequipo',
            name='equipo',
        ),
        migrations.AlterUniqueTogether(
            name='reservaequipo',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reservaequipo',
            name='reserva',
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='incidencia',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='laboratorio',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='penalizacion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='ReservaEquipo',
        ),
    ]
