# Generated by Django 5.2.13 on 2026-05-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_pbi07_pbi11_penalizacion_recordatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='activolaboratorio',
            name='columna',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activolaboratorio',
            name='fila',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='tipo_layout',
            field=models.CharField(choices=[('GRID', 'Cuadrícula Clásica'), ('MESAS', 'Mesas de Trabajo')], default='GRID', max_length=10),
        ),
        migrations.AlterField(
            model_name='activolaboratorio',
            name='estado',
            field=models.CharField(choices=[('Operativo', 'Operativo'), ('Mantenimiento', 'Mantenimiento'), ('Dado de baja', 'Dado de baja')], max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada'), ('Completada', 'Completada'), ('No-show', 'No-show')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='horariodisponible',
            index=models.Index(fields=['fecha', 'estado'], name='horario_fecha_estado_idx'),
        ),
        migrations.AddIndex(
            model_name='horariodisponible',
            index=models.Index(fields=['fecha'], name='horario_fecha_idx'),
        ),
        migrations.AddConstraint(
            model_name='activolaboratorio',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['Operativo', 'Mantenimiento', 'Dado de baja'])), name='activo_estado_valido'),
        ),
    ]
