"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# -----------------------------------------------------------------------------
# Carga de variables desde un archivo .env local (solo desarrollo).
# No sobrescribe variables ya presentes en el entorno (en Cloud Run / Docker /
# CI mandan las variables reales). Si no existe .env, no hace nada.
# -----------------------------------------------------------------------------
_env_file = BASE_DIR / '.env'
if _env_file.exists():
    for _line in _env_file.read_text(encoding='utf-8').splitlines():
        _line = _line.strip()
        if not _line or _line.startswith('#') or '=' not in _line:
            continue
        _key, _, _val = _line.partition('=')
        os.environ.setdefault(_key.strip(), _val.strip().strip('"').strip("'"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').strip().lower() in ('true', '1', 'yes', 'on')

# SECURITY WARNING: keep the secret key used in production secret!
# En desarrollo (DEBUG=True) se permite una clave por defecto; en producción
# (DEBUG=False) la variable de entorno SECRET_KEY es obligatoria.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-desarrollo-local-no-usar-en-pro'
    else:
        raise ImproperlyConfigured(
            'La variable de entorno SECRET_KEY es obligatoria cuando DEBUG=False. '
            'Defínela en el entorno de despliegue (Cloud Run / Docker / CI).'
        )

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Agrega esta lista con la URL exacta de Render
CSRF_TRUSTED_ORIGINS = os.environ.get(
    'CSRF_TRUSTED_ORIGINS',
    'https://labsync-backend-90371338218.us-central1.run.app'
).split(',')

cors_env = os.environ.get(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:3000,http://localhost:5173,https://labsync-untels.vercel.app'
)
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_env.split(',')]
if 'https://labsync-untels.vercel.app' not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append('https://labsync-untels.vercel.app')
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'reservas',
    "corsheaders",
    'drf_spectacular',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # S-1 (CWE-352): exige cabecera no-simple (X-Requested-With) en las peticiones
    # que mutan estado y se autentican por cookie, forzando preflight CORS y
    # bloqueando así los ataques CSRF cross-site.
    'reservas.utils.security.RequireRequestedWithForCookieAuthMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = False      # ID-08: usa la whitelist de CORS_ALLOWED_ORIGINS
CORS_ALLOW_CREDENTIALS = True       # C-2: necesario para que el navegador envíe la cookie auth_token en cross-origin

# =============================================================================
# S-5 · HARDENING DE SEGURIDAD (solo activo en producción, DEBUG=False)
# =============================================================================
# Evita degradar la seguridad en local (HTTP) pero la fuerza en despliegue.
SECURE_CONTENT_TYPE_NOSNIFF = True
if not DEBUG:
    # Cloud Run / proxies terminan TLS y reenvían el esquema en esta cabecera.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000          # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

#Configuración para PostgreSQL
import dj_database_url
import sys

# Si ejecutamos las pruebas, usamos SQLite para evitar errores de codificación en Windows con psycopg2
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    # Disable SSL redirect in tests to prevent 301 responses when using HTTP test client
    SECURE_SSL_REDIRECT = False
else:
    # Render provee DATABASE_URL automáticamente. Usamos el string local como fallback en desarrollo.
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=60,
            conn_health_checks=False,
        )
    }





# =============================================================================
# CACHE (P-3)
# =============================================================================
# Throttling (S-3) y el caché de activos usan este backend. En producción con
# varios workers de gunicorn, LocMemCache es por-proceso y no comparte estado;
# si se define REDIS_URL se usa un caché compartido (backend nativo de Django,
# sin dependencias extra). En local cae a LocMemCache.
_redis_url = os.environ.get('REDIS_URL')
if _redis_url:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': _redis_url,
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuración de WhiteNoise para compresión y cache
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# S-6: sin credenciales por defecto. Si no se configuran, el envío de correo
# simplemente fallará de forma controlada (ya está manejado en el código).
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# =============================================================================
# CONFIGURACIÓN DE LOGGING (PBI-18 — PRIVACIDAD)
# =============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'mask_pii': {
            '()': 'reservas.utils.logging_filters.PIIMaskingFilter',
        },
    },
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['mask_pii'],
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'reservas': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'reservas.utils.auth.CustomTokenAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'login': '5/min',
        # S-3: limitar fuerza bruta sobre recuperación/verificación de código.
        'forgot_password': '5/hour',
        'verify_token': '20/hour',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'LabSync UNTELS API',
    'DESCRIPTION': 'Documentación OpenAPI 3.0 generada con drf-spectacular',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
