databases:
  - name: labsync-db
    databaseName: LabSyncUNTELS
    user: labsync_user
    plan: free

services:
  # Backend Service
  - type: web
    name: labsync-backend
    env: python
    plan: free
    region: ohio
    buildCommand: |
      cd backend
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate
    startCommand: |
      cd backend
      gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: labsync-db
          property: connectionString
      - key: DJANGO_DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "labsync-backend.onrender.com,labsync-backend-90371338218.us-central1.run.app"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://labsync-backend.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://labsync-frontend.onrender.com"

  # Frontend Service
  - type: web
    name: labsync-frontend
    env: static
    plan: free
    region: ohio
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        # Reemplazar con la URL real después del primer despliegue
        value: "https://labsync-backend.onrender.com"
